language: objective-c
osx_image: xcode10.2
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -project UIComponentLibrary.xcodeproj -scheme UIComponentLibrary -sdk $TEST_SDK -destination "platform=iOS Simulator" ONLY_ACTIVE_ARCH=YES
- pod lib lint
